//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalFour
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jogos()
        {
            this.Torneios = new HashSet<Torneios>();
            this.Torneios1 = new HashSet<Torneios>();
            this.Torneios2 = new HashSet<Torneios>();
        }
    
        public int Id_Jogo { get; set; }
        public int Id_ClubeDaCasa { get; set; }
        public int Id_ClubeVisitente { get; set; }
        public System.DateTime InicioJogo { get; set; }
        public int ResultadoClubeDaCasa { get; set; }
        public int ResultadoClubeVisitente { get; set; }
        public string EstadioDoJogo { get; set; }
    
        public virtual ClubesFutebol ClubesFutebol { get; set; }
        public virtual ClubesFutebol ClubesFutebol1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Torneios> Torneios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Torneios> Torneios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Torneios> Torneios2 { get; set; }
    }
}
