//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalFour
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tecnicos
    {
        public string Nif { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public string Contacto { get; set; }
        public string Email { get; set; }
        public decimal Salario { get; set; }
        public System.DateTime InicioContrato { get; set; }
        public System.DateTime FimContrato { get; set; }
        public int Ncarteira { get; set; }
        public int id_tipoTec { get; set; }
        public int NumGrauTec { get; set; }
        public int id_Clube { get; set; }
    
        public virtual ClubesFutebol ClubesFutebol { get; set; }
        public virtual TiposTecnicos TiposTecnicos { get; set; }
    }
}
